version: '3.8'

services:
  frontend:
    image: spooky-trips-nextjs-prod-imagee
    container_name: host-spooky-trips-nextjs-prod-frontend
    build:
      context: ./frontend
      dockerfile: ../provision/frontend/production/Dockerfile
    ports:
      - ${NEXT_PUBLIC_APP_PORT}:3000
    depends_on:
      - backend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env

  backend:
    image: spooky-trips-nestjs-prod-image
    container_name: host-spooky-trips-nestjs-prod-backend
    build:
      context: ./backend
      dockerfile: ../provision/backend/production/Dockerfile
    ports:
      - ${NEST_PORT}:${NEST_PORT}
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
